version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: agroflow-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # Puerto AMQP
      - "15672:15672"  # Puerto Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - agroflow-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  rabbitmq_data:
    driver: local

networks:
  agroflow-network:
    driver: bridge