apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: agroflow-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "agroflow_inventory"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"  # Conexión a RabbitMQ
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: agroflow-namespace
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-service-ingress
  namespace: agroflow-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: agroflow.local
    http:
      paths:
      - path: /api/inventory
        pathType: Prefix
        backend:
          service:
            name: inventory-service
            port:
              number: 8081
