apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventario
  namespace: agroflow-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-inventario
  template:
    metadata:
      labels:
        app: ms-inventario
    spec:
      containers:
        - name: ms-inventario
          image: greinoso/ms-inventario:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "agroflow_inventory"
            - name: RABBITMQ_URL
              value: "amqp://admin:admin123@localhost:5672"  
---
apiVersion: v1
kind: Service
metadata:
  name: ms-inventario
  namespace: agroflow-namespace
spec:
  selector:
    app: ms-inventario
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-inventario-ingress
  namespace: agroflow-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: agroflow.local
    http:
      paths:
      - path: /api/insumos
        pathType: Prefix
        backend:
          service:
            name: ms-inventario
            port:
              number: 3002
