apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventario
  namespace: agroflow-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-inventario
  template:
    metadata:
      labels:
        app: ms-inventario
    spec:
      containers:
        - name: ms-inventario
          image: greinoso/ms-inventario:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-inventario-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-inventario-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-inventario-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-inventario-config
                  key: DB_PORT
            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: postgres-inventario-config
                  key: DB_DIALECT
            - name: RABBITMQ_URL
              value: "amqp://admin:admin123@rabbitmq:5672"  
---
apiVersion: v1
kind: Service
metadata:
  name: ms-inventario
  namespace: agroflow-namespace
spec:
  selector:
    app: ms-inventario
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-inventario-ingress
  namespace: agroflow-namespace
spec:
  rules:
  - host: agroflow.local
    http:
      paths:
      - path: /api/insumos
        pathType: Prefix
        backend:
          service:
            name: ms-inventario
            port:
              number: 3002
